version: "3"
services:
  redis_service:
    image: redis:6.2-alpine
    command: /bin/sh -c "redis-server --port 6000 --requirepass $$REDIS_PASSWORD"
    container_name: redis_service
    restart: unless-stopped
    env_file:
      - redis.env

  web_app:
    depends_on:
      - redis_service
    container_name: uni_shortener
    build: .
    restart: unless-stopped
#    ports:
#      - "8000:8000"
    volumes:
      - ${DB_PATH}:/uni_shortener/database
      - ${LOGS_PATH}:/uni_shortener/logs
      - static_files:/uni_shortener/static
    env_file:
      - .env
      - redis.env

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_files:/uni_shortener/static
    depends_on:
      - web_app

volumes:
  static_files:
